CREATE TABLE ENVIRONMENTS
(
  ID            INTEGER NOT NULL,
  NAME          CHAR(100),
  CREATED_DATE  DATE,
  MODIFIED_DATE DATE,
  PRIMARY KEY (ID)
);

CREATE TABLE HOSTS
(
  ID            INTEGER NOT NULL,
  IP            CHAR(50),
  NAME          CHAR(100),
  CREATED_DATE  DATE,
  MODIFIED_DATE DATE,
  PRIMARY KEY (ID)
)